"""Regenerate the static demo reports published under the docs site (/demo/).

    python scripts/fetch_models.py --only family_   # the pinned family model (SHA-256 verified)
    python scripts/build_demo.py

Runs ``specimen report`` on the bundled, trimmed Avast-CTU fixtures and
``specimen analyze`` on the Sysmon lab fixture, and writes Markdown pages to
``docs/demo/`` plus ``docs/demo/summary.json`` (verdicts, family evidence and
one rule per input), from which ``scripts/render_results.py`` fills the README
example and the How-it-works walkthrough. Inputs are sandbox reports / event
logs only; nothing is executed.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from specimen import __version__  # noqa: E402
from specimen.pipeline import family_model, run, run_report  # noqa: E402
from specimen.report import render_markdown  # noqa: E402

OUT = ROOT / "docs" / "demo"
CAPE = ["avast_njrat_1", "avast_emotet_1", "avast_lokibot_1", "full_cape_synthetic"]


def page(title: str, note: str, rep: dict) -> str:
    md = render_markdown(rep).split("\n", 1)[1]
    return f"# {title}\n\n!!! note\n    {note}\n{md}"


def summary(rep: dict) -> dict:
    b = rep["behavior"] or {}
    sig = rep["detections"]["sigma"]
    return {"verdict": rep["verdict"], "static_score": rep["static"]["score"],
            "static_top": rep["static"]["top_reasons"][:2], "behaviour_scorer": b.get("scorer"),
            "behaviour_p": b.get("probability"), "behaviour_top": (b.get("contributions") or [])[:3],
            "family": b.get("family"), "family_p": b.get("family_similarity"), "family_model": b.get("family_model"),
            "family_evidence": (b.get("family_evidence") or [])[:4], "techniques": rep["techniques"],
            "sigma_rules": len(sig), "first_sigma": sig[0] if sig else None, "yara": bool(rep["detections"]["yara"]),
            "graph": rep["graph"], "timeline_head": [t for t in rep["timeline"] if t["technique"]][:4],
            "manifest": {k: rep["manifest"].get(k) for k in ("specimen_version", "negative_corpus", "trace_binding")}}


def _repo_relative(obj):
    """Rewrite absolute paths under the checkout as repo-relative ones so pages do not leak local paths."""
    if isinstance(obj, dict):
        return {k: _repo_relative(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_repo_relative(v) for v in obj]
    if isinstance(obj, str) and obj.startswith(str(ROOT)):
        return Path(obj).relative_to(ROOT).as_posix()
    return obj


def run_report_rel(path):
    return _repo_relative(run_report(path))


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    rows, summ = [], {}
    for name in CAPE:
        rep = run_report_rel(ROOT / "tests" / "fixtures" / "cape" / f"{name}.json")
        rep["sample"]["path"] = f"tests/fixtures/cape/{name}.json"
        (OUT / f"{name}.md").write_text(page(f"Report: {name}", "Generated by `specimen report` from a bundled "
                                             "fixture (trimmed public Avast-CTU report, or a synthetic one).", rep),
                                        encoding="utf-8", newline="\n")
        b = rep["behavior"] or {}
        rows.append((name, rep["verdict"]["label"], rep["verdict"]["score"], b.get("family"),
                     len(rep["detections"]["sigma"]), bool(rep["detections"]["yara"])))
        summ[name] = summary(rep)
    # the Sysmon fixture is bound to this inert dummy file (event 1 Hashes SHA256)
    sample = ROOT / "tests" / "fixtures" / "sysmon" / "lab_sample.bin"
    rep = _repo_relative(run(sample, ROOT / "tests" / "fixtures" / "sysmon" / "lab_run.xml", force_detonate=True))
    rep["sample"]["path"] = "tests/fixtures/sysmon/lab_sample.bin + lab_run.xml"
    (OUT / "sysmon_lab_run.md").write_text(page("Report: Sysmon lab run", "Generated by `specimen analyze "
                                                "--force-detonate` from the inert lab_sample.bin and the synthetic "
                                                "Sysmon XML export bound to it.", rep), encoding="utf-8", newline="\n")
    b = rep["behavior"] or {}
    rows.append(("sysmon_lab_run", rep["verdict"]["label"], rep["verdict"]["score"], b.get("family"),
                 len(rep["detections"]["sigma"]), bool(rep["detections"]["yara"])))
    summ["sysmon_lab_run"] = summary(rep)
    fm = family_model()
    model = (f"family model `{fm.meta.get('variant', '?')}`, abstain below {fm.meta.get('abstain_below')}"
             if fm is not None else "no family model installed")
    L = ["# Demo reports", "",
         "Static pages generated by `python scripts/build_demo.py` from the small inputs committed under "
         f"`tests/fixtures/`, with SPECIMEN {__version__} and the pinned {model} (`scripts/model_assets.json`). "
         "They show exactly what `specimen report` / `specimen analyze` write; nothing here was executed.", "",
         "| input | verdict | score | family | Sigma rules | YARA |", "|---|---|---|---|---|---|"]
    L += [f"| [{n}]({n}.md) | {v} | {s} | {f or '-'} | {k} | {'yes' if y else 'no'} |" for n, v, s, f, k, y in rows]
    (OUT / "index.md").write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    (OUT / "summary.json").write_text(json.dumps({"specimen_version": __version__, "family_model": model,
                                                  "inputs": summ}, indent=1, sort_keys=True) + "\n",
                                      encoding="utf-8", newline="\n")
    print(f"wrote {len(rows)} demo reports to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
