"""Regenerate the static demo reports published under the docs site (/demo/).

    python scripts/build_demo.py

Runs ``specimen report`` on the bundled, trimmed Avast-CTU fixtures and the
Sysmon lab fixture, and writes Markdown pages to ``docs/demo/``. Inputs are
sandbox reports / event logs only; nothing is executed.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from specimen.pipeline import run, run_report  # noqa: E402
from specimen.report import render_markdown  # noqa: E402

OUT = ROOT / "docs" / "demo"
CAPE = ["avast_njrat_1", "avast_emotet_1", "avast_lokibot_1", "full_cape_synthetic"]


def page(title: str, note: str, rep: dict) -> str:
    md = render_markdown(rep).split("\n", 1)[1]
    return f"# {title}\n\n!!! note\n    {note}\n{md}"


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    rows = []
    for name in CAPE:
        rep = run_report(ROOT / "tests" / "fixtures" / "cape" / f"{name}.json")
        rep["sample"]["path"] = f"tests/fixtures/cape/{name}.json"
        (OUT / f"{name}.md").write_text(page(f"Report: {name}", "Generated by `specimen report` from a bundled "
                                             "fixture (trimmed public Avast-CTU report, or a synthetic one).", rep),
                                        encoding="utf-8")
        b = rep["behavior"] or {}
        rows.append((name, rep["verdict"]["label"], rep["verdict"]["score"], b.get("family"),
                     len(rep["detections"]["sigma"]), bool(rep["detections"]["yara"])))
    # the Sysmon fixture is bound to this inert dummy file (event 1 Hashes SHA256)
    sample = ROOT / "tests" / "fixtures" / "sysmon" / "lab_sample.bin"
    rep = run(sample, ROOT / "tests" / "fixtures" / "sysmon" / "lab_run.xml", force_detonate=True)
    rep["sample"]["path"] = "tests/fixtures/sysmon/lab_sample.bin + lab_run.xml"
    (OUT / "sysmon_lab_run.md").write_text(page("Report: Sysmon lab run", "Generated by `specimen analyze "
                                                "--force-detonate` from the inert lab_sample.bin and the synthetic Sysmon XML "
                                                "export bound to it.", rep), encoding="utf-8")
    b = rep["behavior"] or {}
    rows.append(("sysmon_lab_run", rep["verdict"]["label"], rep["verdict"]["score"], b.get("family"),
                 len(rep["detections"]["sigma"]), bool(rep["detections"]["yara"])))
    L = ["# Demo reports", "",
         "Static pages generated by `python scripts/build_demo.py` from the small inputs committed under "
         "`tests/fixtures/`. They show exactly what `specimen report` / `specimen analyze` write; nothing here "
         "was executed.", "",
         "| input | verdict | score | family | Sigma rules | YARA |", "|---|---|---|---|---|---|"]
    L += [f"| [{n}]({n}.md) | {v} | {s} | {f or '-'} | {k} | {'yes' if y else 'no'} |" for n, v, s, f, k, y in rows]
    (OUT / "index.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {len(rows)} demo reports to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
